### ISSUE TITLE
"social" category added for posts without titles

### ISSUE THREAD

**Issue by barryf** [voxpelli/webpage-micropub-to-github#4]
When I post a note without a title a category of "social" is added. I think this may originate via your node-format-microformat project.

**Comment by voxpelli** [comment]
Yeah, this is due to `node-format-microformat` not yet being very customizable but currently mostly configured for my own dogfooding needs and I use the `social` category to differentiate between my social posts (http://voxpelli.com/social/), my shared links (http://voxpelli.com/links/) and my regular blog posts (http://voxpelli.com/). And a title less post == a tweetish note, which goes into the `social` category for me.

I guess a simple way to avoid you getting those categories when you use the endpoint would be to just add a toggle which can disable or enable the addition of `social` and `links` categories to Micropub-created posts. Does that sounds like a good solution to you? Or do you maybe want to split up content as well but just in another way than me?

**Comment by miklb** [comment]
A config to be able to set the categories would be nice.

**Comment by miklb** [comment]
@voxpelli have you put any more thought into this? Also wondering about being able to add an additional category or tag for photo posts so I can display or sort them separately.

**Comment by voxpelli** [comment]
@miklb My current thinking is that a new callback in format-microformat would do it there and then in this project some optional JSON-object to define how things could be resolved could be added. The JSON-object or similar would just be to make it fit into a a .env variable so not really something that format-microformat would have to be concerned with.

**Comment by voxpelli** [comment]
I went somewhat overkill here now created a new module for this: [fulfills](https://www.npmjs.com/package/fulfills)

So now one can specify the `MICROPUB_OPTION_DERIVE_CATEGORY` env variable to something like:

```json
{
  "categoryName": "prop.erty.chain. != foobar",
  "bookmark": "bookmark OR markboo",
  "complex": "!(bookmark.bar-car.foo[\"abc adf sdaf sda f\"][][][]=123) AND foo OR bar=abc OR foo=\"\\\\\" OR foo[]=123 OR foo.abc[].bar.foo[] != true"
}
```

The condition is against the properties of the document that's sent in and the keys in the object are the category that will be set if a condition is true.

Only a single category is supported until #7 is fixed.

Please ask how a condition can be written for the categories that you want to be specified.
